name: JS Actions

on:
  issues:
    types: [labeled]

jobs:
  action:
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: ha-ha
        id: ha
        uses: ./.github/actions/joke-action
      - name: Get the output time
        run: echo "repeating the joke from actions script ${{ steps.ha.outputs.joke }}"
