name: JS Actions

on:
  issues:
    types: [labeled]

jobs:
  action:
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: ha-ha
        id: ha
        uses: ./.github/actions/joke-action
      - name: comment joke
        id: commentedjoke
        uses: mvkaran/comment-on-issue@v1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABEL: 'first joke'
          COMMENT: 'Joke: ${{ steps.ha.outputs.joke }}'
