name: "Generate and comment joke"

on:
  issues:
    types: [labeled]

jobs:
  generate-joke:
    name: Generate-Joke
    runs-on: ubuntu-latest
    
    outputs:
      storedjoke: ${{ steps.store-joke.outputs.storedjoke }}
    steps:
      - uses: actions/checkout@v3
      - name: ha-ha
        id: ha
        uses: ./.github/actions/joke-action
      - name: Store joke output
        id: store-joke
        run: echo "storedjoke=${{ steps.ha.outputs.joke }}" >> $GITHUB_OUTPUT
          
  comment-joke:
    needs: generate-joke
    name: Comment-Joke
    runs-on: ubuntu-latest
    
    steps:
      - name: Check for find-comment
        run: echo "This is the input of the joke ${{ needs.generate-joke.outputs.storedjoke }}
      
      #- name: comment joke
        #id: commentedjoke
        #uses: mvkaran/comment-on-issue@v1.0
        #env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #LABEL: 'first joke'
          #COMMENT: 'Joke: ${{ steps.ha.outputs.joke }}'
      
      
